# Generated by Django 3.2 on 2021-05-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_status', models.CharField(choices=[('R', 'Rent'), ('B', 'Buy'), ('M', 'Mortgage')], max_length=1, verbose_name='وضعیت خرید')),
                ('estate_status', models.CharField(choices=[('R', 'Residential'), ('C', 'Commercial')], max_length=1, verbose_name='وضعیت ملک')),
                ('building_status', models.CharField(choices=[('V', 'Villa'), ('A', 'Apartment')], max_length=1, verbose_name='وضعیت ساختمان')),
                ('area_size', models.IntegerField(blank=True, null=True, verbose_name='متراژ')),
                ('roomـqty', models.IntegerField(blank=True, null=True, verbose_name='تعداد اتاق')),
                ('parking', models.BooleanField(default=True, verbose_name='پارکینگ')),
                ('storage_room', models.BooleanField(default=True, verbose_name='انباری')),
                ('building_age', models.IntegerField(blank=True, null=True, verbose_name='سن بنا')),
                ('elevator', models.BooleanField(default=False, verbose_name='آسانسور')),
                ('balcony', models.BooleanField(default=False, verbose_name='بالکن')),
                ('image', models.ImageField(blank=True, default='media/Default.png', null=True, upload_to='media', verbose_name='تصویر')),
                ('additional_Information', models.TextField(blank=True, max_length=1000, null=True, verbose_name='اطلاعات تکمیلی')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='شهر')),
                ('neighbourhood', models.CharField(blank=True, max_length=50, null=True, verbose_name='محله')),
            ],
            options={
                'verbose_name': 'ملک',
                'verbose_name_plural': 'املاک',
            },
        ),
    ]
