# Generated by Django 3.2 on 2021-05-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Rent',
            field=models.IntegerField(blank=True, null=True, verbose_name='اجاره'),
        ),
        migrations.AddField(
            model_name='item',
            name='deposit',
            field=models.IntegerField(blank=True, null=True, verbose_name='پول پیش'),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت خرید '),
        ),
        migrations.AlterField(
            model_name='item',
            name='building_status',
            field=models.CharField(choices=[('ویلایی', 'Villa'), ('اپارتمانی', 'Apartment')], max_length=10, verbose_name='وضعیت ساختمان'),
        ),
        migrations.AlterField(
            model_name='item',
            name='buy_status',
            field=models.CharField(choices=[('اجاره', 'Rent'), ('خرید', 'Buy'), ('رهن', 'Mortgage')], max_length=10, verbose_name='وضعیت خرید'),
        ),
        migrations.AlterField(
            model_name='item',
            name='estate_status',
            field=models.CharField(choices=[('مسکونی', 'Residential'), ('تجاری', 'Commercial')], max_length=15, verbose_name='وضعیت ملک'),
        ),
    ]
